signal33_site/__init__.py
from flask import Flask


app = Flask(__name__)


#register context processors

from template_ext.form import proc
app.register_blueprint(proc)

#register controllers
from controllers import homecontroller

app.register_blueprint(homecontroller.ctrl)

signal33_site/controllers/homecontroller.py
from flask import Blueprint, render_template, request, redirect, url_for

from models import usermodel, addressmodel


ctrl = Blueprint('home', __name__)


@ctrl.route('/')
def index():
    return render_template('home/index.html')


@ctrl.route('/about')
def about():
    return render_template('home/about.html')

@ctrl.route('/contact')
def contact():
    return render_template('home/contact.html')

@ctrl.route('/logon')
def logon():
    return render_template('home/logon.html')

@ctrl.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        user = usermodel.UserRegisterModel()
        user.city = request.form['txtCity']
        user.confirm_email_address = request.form['txtConfirmEmailAddress']
        user.email_address = request.form['txtEmailAddress']
        user.first_name = request.form['txtFirstName']
        user.last_name = request.form['txtLastName']
        #user.state = request.form['txtState']
        user.street = request.form['txtStreet']
        user.street2 = request.form['txtStreet2']
        user.user_name = request.form['txtUserName']
        user.zip = request.form['txtZip']

        #TODO: look into secure password handling
        user.password = request.form['txtPassword']
        user.confirm_password = request.form['txtConfirmPassword']
        return redirect(url_for('home.index'))
    return render_template('home/register.html')

signal33_site/templates/home/about.html
{% extends "layout.html" %}
{% block title %}{% endblock %}
{% block styles %}{% endblock %}
{% block top_scripts %}{% endblock %}
{% block content %}

{% endblock %}

signal33_site/templates/home/contact.html
{% extends "layout.html" %}
{% block title %}{% endblock %}
{% block styles %}{% endblock %}
{% block top_scripts %}{% endblock %}
{% block content %}

{% endblock %}

signal33_site/templates/home/index.html
{% extends "layout.html" %}
{% block title %}signal 33 technologies{% endblock %}
{% block styles %}{% endblock %}
{% block top_scripts %}{% endblock %}
{% block content %}
<h2>signal 33 technologies</h2>
{% endblock %}

signal33_site/templates/home/logon.html
{% extends "layout.html" %}
{% block title %}{% endblock %}
{% block styles %}{% endblock %}
{% block top_scripts %}{% endblock %}
{% block content %}

{% endblock %}

signal33_site/templates/home/register.html
{% extends "layout.html" %}
{% block title %}{% endblock %}
{% block styles %}{% endblock %}
{% block top_scripts %}{% endblock %}
{% block content %}
<form id="frmRegister" name="frmRegister" action="{{ url_for('home.register') }}" method="post">
    <label for="txtUserName">txtUserName</label>
    <input type="text" id="txtUserName" name="txtUserName" />
    <br />
    <label for="txtFirstName">txtFirstName</label>
    <input type="text" id="txtFirstName" name="txtFirstName" maxlength="50" />
    <br />
    <label for="txtLastName">txtLastName</label>
    <input type="text" id="txtLastName" name="txtLastName" maxlength="50" />
    <br />
    <label for="txtEmailAddress">txtEmailAddress</label>
    <input type="email" id="txtEmailAddress" name="txtEmailAddress" maxlength="50" />
    <br />
    <label for="txtConfirmEmailAddress">txtConfirmEmailAddress</label>
    <input type="email" id="txtConfirmEmailAddress" name="txtConfirmEmailAddress" maxlength="50" />
    <br />
    <label for="txtStreet">txtStreet</label>
    <input type="text" id="txtStreet" name="txtStreet" />
    <br />
    <label for="txtStreet2">txtStreet2</label>
    <input type="text" id="txtStreet2" name="txtStreet2" />
    <br />
    <label for="txtCity">txtCity</label>
    <input type="text" id="txtCity" name="txtCity" maxlength="50" />
    <br />

    <br />
    <label for="txtZip">txtZip</label>
    <input type="text" id="txtZip" name="txtZip" />
    <br />
    <label for="txtPassword">txtPassword</label>
    <input type="password" id="txtPassword" name="txtPassword" />
    <br />
    <label for="txtConfirmPassword">txtConfirmPassword</label>
    <input type="password" id="txtConfirmPassword" name="txtConfirmPassword" />
    <br />
    <input type="submit" id="btnSubmit" name="btnSubmit" value="Submit" />
</form>
{% endblock %}
{% block scripts %}
    <script type="text/javascript">

    </script>
{% endblock %}

signal33_site/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}{% endblock %}
    {% block top_scripts %}{% endblock %}
    <script type="text/javascript" src="./register" ></script>
</head>
<body>
    <div>
        <div id="divHeader"></div>
        <div id="divTopNav"></div>
        <div id="divLeftBar"></div>
        <div id="divContent">
            {% block content %}{% endblock %}
        </div>
        <div id="divFooter"></div>
    </div>
    <div>
        {% block scripts %}{% endblock %}
    </div>
</body>
</html>

signal33_site/templates/template.html
{% extends "layout.html" %}
{% block title %}{% endblock %}
{% block styles %}{% endblock %}
{% block top_scripts %}{% endblock %}
{% block content %}

{% endblock %}
{% block scripts %}{% endblock %}